# Generated by Django 2.0.3 on 2018-03-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZPK', '0002_auto_20180315_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='otdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='sallary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='otdel',
            name='sotrudnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZPK.person'),
        ),
    ]
