# Generated by Django 2.0.3 on 2018-03-28 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZPK', '0007_auto_20180316_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choise_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='otdel',
            name='sotrudnik',
        ),
        migrations.DeleteModel(
            name='otdel',
        ),
        migrations.DeleteModel(
            name='person',
        ),
        migrations.AddField(
            model_name='choise',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZPK.Question'),
        ),
    ]
