# Generated by Django 2.0.3 on 2018-04-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZPK', '0009_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Sallary',
            field=models.IntegerField(),
        ),
    ]
