# Generated by Django 2.0.3 on 2018-04-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZPK', '0011_auto_20180404_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
