# Generated by Django 2.0.3 on 2018-04-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZPK', '0012_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZpkPhoneInner', models.CharField(max_length=50, null=True)),
                ('ZpkPhoneOuter', models.CharField(max_length=50, null=True)),
                ('PrivatePhone', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=100, null=True)),
                ('FirstName', models.CharField(max_length=100, null=True)),
                ('Doljnost', models.CharField(max_length=100, null=True)),
                ('Otdel', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
