# Generated by Django 2.0.3 on 2018-04-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZPK', '0014_auto_20180412_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebook',
            name='FIO',
        ),
        migrations.AddField(
            model_name='phonebook',
            name='FirstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phonebook',
            name='LastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
