# Generated by Django 2.0.3 on 2018-04-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZPK', '0016_auto_20180412_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='Doljnost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='FIO',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='Otdel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='PrivatePhone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='ZpkPhoneInner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='ZpkPhoneOuter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
