# Generated by Django 2.0.3 on 2018-04-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0004_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Account',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Comissioning',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='FactoryNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='InvNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Lifetime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='MOL',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
