# Generated by Django 2.0.3 on 2018-04-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0013_auto_20180406_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
