# Generated by Django 2.0.3 on 2018-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0015_auto_20180410_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='FactoryNum',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
