# Generated by Django 2.0.3 on 2018-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0016_auto_20180410_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Comissioning',
            field=models.DateTimeField(null=True),
        ),
    ]
