# Generated by Django 2.0.3 on 2018-04-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0018_auto_20180410_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Comissioning',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
