# Generated by Django 2.0.3 on 2018-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('Info', models.CharField(blank=True, max_length=20000, null=True)),
                ('Pubdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
