# Generated by Django 2.0.3 on 2018-04-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_auto_20180417_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='Info',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='Pubdate',
        ),
    ]
