# Generated by Django 2.0.3 on 2018-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_auto_20180417_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='Info',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='Photo',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='', width_field=750),
        ),
        migrations.AddField(
            model_name='ship',
            name='Pubdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
