# Generated by Django 2.0.3 on 2018-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_auto_20180417_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='ships2'),
        ),
    ]
