# Generated by Django 2.0.3 on 2018-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_auto_20180417_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='Photo',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='ships', width_field=300),
        ),
    ]
