# Generated by Django 2.0.3 on 2018-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_auto_20180417_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='Content',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
