# Generated by Django 2.0.3 on 2018-04-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='ContentEng',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
