# Generated by Django 2.0.3 on 2018-04-26 07:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0014_ship_contenteng'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='Test',
            field=tinymce.models.HTMLField(blank=True, max_length=100000, null=True),
        ),
    ]
